2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_setup.py:_flush():67] Configure stats pid to 1586630
2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_setup.py:_flush():67] Loading settings from /home/yyf/.config/wandb/settings
2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_setup.py:_flush():67] Loading settings from /home/yyf/github/luckyrobot/wandb/settings
2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-27 18:32:47,963 INFO    MainThread:1586630 [wandb_init.py:setup_run_log_directory():647] Logging user logs to experiments/run_20250227_183247/wandb/run-20250227_183247-cc0cyrjt/logs/debug.log
2025-02-27 18:32:47,964 INFO    MainThread:1586630 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to experiments/run_20250227_183247/wandb/run-20250227_183247-cc0cyrjt/logs/debug-internal.log
2025-02-27 18:32:47,964 INFO    MainThread:1586630 [wandb_init.py:init():761] calling init triggers
2025-02-27 18:32:47,964 INFO    MainThread:1586630 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'num_train_envs': 1, 'num_test_envs': 1, 'actor_hidden_sizes': [256, 256, 256], 'critic_hidden_sizes': [256, 256, 256], 'actor_lr': 0.001, 'critic_lr': 0.001, 'gamma': 0.99, 'tau': 0.005, 'alpha': 0.2, 'n_step_returns': 1, 'max_epoch': 100, 'step_per_epoch': 100, 'step_per_collect': 100, 'update_per_step': 0.1, 'batch_size': 256, 'buffer_size': 20000, 'episode_per_test': 1, 'target_reward': 180, 'save_interval': 10, 'log_interval': 1, 'exp_name': 'reach_grasp_baseline', 'notes': 'Baseline SAC implementation for reach-grasp task', '_wandb': {}}
2025-02-27 18:32:47,964 INFO    MainThread:1586630 [wandb_init.py:init():784] starting backend
2025-02-27 18:32:47,964 INFO    MainThread:1586630 [wandb_init.py:init():788] sending inform_init request
2025-02-27 18:32:47,965 INFO    MainThread:1586630 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-27 18:32:47,965 INFO    MainThread:1586630 [wandb_init.py:init():803] backend started and connected
2025-02-27 18:32:47,966 INFO    MainThread:1586630 [wandb_init.py:init():896] updated telemetry
2025-02-27 18:32:47,968 INFO    MainThread:1586630 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-27 18:32:48,368 INFO    MainThread:1586630 [wandb_init.py:init():995] starting run threads in backend
2025-02-27 18:32:48,404 INFO    MainThread:1586630 [wandb_run.py:_console_start():2377] atexit reg
2025-02-27 18:32:48,405 INFO    MainThread:1586630 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-27 18:32:48,405 INFO    MainThread:1586630 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-27 18:32:48,405 INFO    MainThread:1586630 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-27 18:32:48,405 INFO    MainThread:1586630 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-27 18:32:51,915 WARNING MsgRouterThr:1586630 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/yyf/miniconda3/envs/luckyrobot/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/yyf/miniconda3/envs/luckyrobot/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/yyf/miniconda3/envs/luckyrobot/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yyf/miniconda3/envs/luckyrobot/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/yyf/miniconda3/envs/luckyrobot/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-27 18:32:51,916 INFO    MsgRouterThr:1586630 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
